version: '3.9'

services:
  ruby:
    image: ruby
    working_dir: /app
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
    networks:
      - lenz

volumes:
  rubygems:

networks:
  lenz:
    external: true
